import type { Metadata } from "next";
import { Familjen_Grotesk, Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { Sidebar } from "@/components/nav";
import BaseLayout from "@/components/layouts";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
	subsets: ['latin'],
	weight: '400',
	display: 'swap',
	variable: '--font-inter',
});

const familjenGrotesk = Familjen_Grotesk({
	subsets: ['latin'],
	weight: ['600', '700'], // 600 for semibold, 700 for bold
	display: 'swap',
});


export const metadata: Metadata = {
	title: "Vet AI app",
	description: "Generated by reseachdog AI",
};


export default function RootLayout({
									   children,
								   }: {
	children: React.ReactNode;
}) {
	return (
		<html lang="sv" className={familjenGrotesk.className}>
		<body className="bg-[#fcfdfa] text-[#343437] w-full">
		<BaseLayout>
				{children}
		</BaseLayout>
		</body>
		</html>
	);
}
