import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { Sidebar } from "@/components/nav";
import BaseLayout from "@/components/layouts";

// Define Inter with a CSS variable for Tailwind
const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Vet AI app",
	description: "Generated by reseachdog AI",
};

export default function RootLayout({
									   children,
								   }: {
	children: React.ReactNode;
}) {
	return (
		<html lang="sv" className={inter.variable}>
		<body className="bg-gray-100 text-gray-900">
		<BaseLayout>
			<main className="flex-1 p-4">
				{children}
			</main>
		</BaseLayout>
		</body>
		</html>
	);
}
