import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import i18nConfig from '@/i18nConfig';
import { dir } from 'i18next';
import React from "react";
import { Sidebar } from "@/components/nav";

// Define Inter with a CSS variable for Tailwind
const inter = Inter({
	subsets: ["latin"],
	display: 'swap',
	variable: '--font-inter'
});

export const metadata: Metadata = {
	title: "Vet AI app",
	description: "Generated by reseachdog AI",
};

export function generateStaticParams() {
	return i18nConfig.locales.map(locale => ({locale}));
}

export default function RootLayout({
									   children,
									   params: {locale},
								   }: Readonly<{
	children: React.ReactNode;
	params: {
		locale: string;
	};
}>) {
	return (
		<html lang={locale} dir={dir(locale)}>
		<body>
		<section className={"flex"}>
			<Sidebar />
			{children}
		</section>
		</body>
		</html>
	);
}
